using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using DumpLoader_2._0.Models;

namespace DumpLoader_2._0.Services
{
    /// <summary>
    /// Drives the third-party VPOS Dump Editor (DIG) to apply the "support mode" DirectAccess
    /// edits to a dump before it gets loaded into VPOS.
    ///
    /// Every file DIG needs (dig.ini, support.exml, support.xml, support.vpd) is generated by
    /// this class into a "VPOSManager" folder created alongside the configured DumpEditor.exe -
    /// nothing is read from or expected to already exist on disk beforehand.
    ///
    /// Pipeline:
    ///  1. Write dig.ini (VPP init settings) and support.xml (the DirectAccess edits: the fixed
    ///     "Local speichern" block, plus one block per enabled DumpModificationOptions checkbox).
    ///  2. Write support.exml, pointing its &lt;LoadDump&gt; at the dump the user selected and at
    ///     the dig.ini/TableInfo.xml/Translate files that ship next to DumpEditor.exe.
    ///  3. Run `DumpEditor.exe support.exml -nogui` and wait for it to finish.
    ///  4. DIG writes the edited copy to support.vpd (the original dump is never touched) - that
    ///     path is returned for VPOS to load instead.
    /// </summary>
    public class DumpEditorService
    {
        private const string WorkFolderName = "VPOSManager";

        public async Task<string> CreateEditedDumpAsync(string dumpEditorExePath, string sourceDumpPath, DumpModificationOptions options)
        {
            if (string.IsNullOrEmpty(dumpEditorExePath))
                throw new ArgumentException("Der Pfad zu DumpEditor.exe ist nicht gesetzt. Bitte in den Einstellungen konfigurieren.", nameof(dumpEditorExePath));

            if (!File.Exists(dumpEditorExePath))
                throw new FileNotFoundException("DumpEditor.exe wurde nicht gefunden.", dumpEditorExePath);

            if (string.IsNullOrEmpty(sourceDumpPath))
                throw new ArgumentException("sourceDumpPath must not be empty.", nameof(sourceDumpPath));

            var dumpEditorRoot = Path.GetDirectoryName(Path.GetFullPath(dumpEditorExePath));
            if (string.IsNullOrEmpty(dumpEditorRoot))
                throw new InvalidOperationException("Das Verzeichnis von DumpEditor.exe konnte nicht ermittelt werden.");

            var workFolder = Path.Combine(dumpEditorRoot, WorkFolderName);
            Directory.CreateDirectory(workFolder);

            var digIniPath = Path.Combine(workFolder, "dig.ini");
            var supportXmlPath = Path.Combine(workFolder, "support.xml");
            var supportExmlPath = Path.Combine(workFolder, "support.exml");
            var supportDumpOutputPath = Path.Combine(workFolder, "support.vpd");

            WriteDigIni(digIniPath, dumpEditorRoot);
            WriteSupportXml(supportXmlPath, options);
            WriteSupportExml(supportExmlPath, sourceDumpPath);

            if (File.Exists(supportDumpOutputPath))
            {
                try { File.Delete(supportDumpOutputPath); } catch { /* best effort */ }
            }

            var startInfo = new ProcessStartInfo(dumpEditorExePath)
            {
                Arguments = $"\"{supportExmlPath}\" -nogui",
                UseShellExecute = true,
                WorkingDirectory = dumpEditorRoot,
            };

            using var process = Process.Start(startInfo);
            if (process == null)
                throw new InvalidOperationException("DumpEditor.exe konnte nicht gestartet werden.");

            await process.WaitForExitAsync();

            if (!File.Exists(supportDumpOutputPath))
                throw new FileNotFoundException("DumpEditor hat keine bearbeitete Dump-Datei erzeugt.", supportDumpOutputPath);

            return supportDumpOutputPath;
        }

        /// <summary>
        /// VPP module init settings DIG needs to load the dump. VppPath assumes the standard DIG
        /// layout, where a "VPPs" folder sits directly next to DumpEditor.exe.
        /// </summary>
        private static void WriteDigIni(string path, string dumpEditorRoot)
        {
            var vppPath = Path.Combine(dumpEditorRoot, "VPPs");
            var content =
                "[ProgModuleInit]\r\n" +
                "Size=250\r\n" +
                "HardwareType=8\r\n" +
                "LanguageId=1\r\n" +
                $"VppPath={vppPath}\r\n";

            File.WriteAllText(path, content, new UTF8Encoding(false));
        }

        private static void WriteSupportXml(string path, DumpModificationOptions options)
        {
            var root = new XElement("DIG", new XAttribute("Version", "1.0"));

            // Always included, regardless of which checkboxes are set.
            root.Add(new XComment(" Local speichern - ACHTUNG bei einer POS-PC bitte die Einstellungen in der Datei \"HWPROF.INI\" prüfen! "));
            root.Add(DirectAccess("3", "1", "1", "77", "0"));
            root.Add(DirectAccess("3", "1", "1", "78", "0"));
            root.Add(DirectAccess("3", "1", "1", "83", "0"));
            root.Add(DirectAccess("3", "1", "1", "15", "0"));
            root.Add(DirectAccess("3", "1", "1", "84", "0"));

            if (options.DisablePrint)
            {
                root.Add(new XComment(" Disable Drucken "));
                root.Add(DirectAccess("33", "1", "350", "1", "1"));
            }

            if (options.DisableMyVectron)
            {
                root.Add(new XComment(" Disable myVectron "));
                root.Add(DirectAccess("1021", "1", "1", "3", "0"));
            }

            if (options.DisableVectronConnect)
            {
                root.Add(new XComment(" Disable VectronConnect "));
                root.Add(DirectAccess("780", "1", "1", "1", "Banane"));
                root.Add(DirectAccess("780", "1", "1", "2", "0"));
                root.Add(DirectAccess("780", "1", "1", "12", "0"));
            }

            if (options.DisableLicenseCheck)
            {
                root.Add(new XComment(" Disable Lizenzabruf "));
                root.Add(DirectAccess("695", "1", "1", "1", "0"));
            }

            if (options.DisableBonVito)
            {
                root.Add(new XComment(" Disable bonVito "));
                root.Add(DirectAccess("532", "1", "1", "8", "0"));
            }

            if (options.MyVectronUsernameEnabled)
            {
                root.Add(new XComment(" myVectron Username "));
                root.Add(DirectAccess("1021", "1", "1", "1", options.MyVectronUsername ?? string.Empty));
            }

            if (options.MyVectronPasswordEnabled)
            {
                root.Add(new XComment(" myVectron Password "));
                root.Add(DirectAccess("1021", "1", "1", "2", options.MyVectronPassword ?? string.Empty));
            }

            // Always applied (not opt-in): selects Prod vs. Test server for VectronConnect/myVectron.
            var serverValue = options.IsTestServer ? "1" : "0";
            root.Add(new XComment(options.IsTestServer ? " Server-Umgebung: Test " : " Server-Umgebung: Prod "));
            root.Add(DirectAccess("33", "1", "524", "1", serverValue));
            root.Add(DirectAccess("33", "1", "589", "1", serverValue));

            var doc = new XDocument(new XDeclaration("1.0", "utf-8", null), root);
            using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
            doc.Save(writer);
        }

        private static XElement DirectAccess(string tableNo, string planeNo, string recPos, string fieldNo, string data)
        {
            return new XElement("DirectAccess",
                new XAttribute("TableNo", tableNo),
                new XAttribute("PlaneNo", planeNo),
                new XElement("PutData",
                    new XAttribute("RecPos", recPos),
                    new XAttribute("FieldNo", fieldNo),
                    new XAttribute("Data", data)));
        }

        /// <summary>
        /// Generates the eXml script DIG runs: loads the selected dump using dig.ini +
        /// TableInfo.xml (both shipped next to DumpEditor.exe), imports support.xml's
        /// DirectAccess edits, and saves the result as support.vpd - all relative to the
        /// eXml file's own folder ({exml}) or its parent ({exml-1}, i.e. the DIG install root).
        /// </summary>
        private static void WriteSupportExml(string path, string sourceDumpPath)
        {
            var root = new XElement("DIG", new XAttribute("Version", "1.0"));

            root.Add(new XComment(" Dump file "));
            root.Add(new XElement("LoadDump",
                new XAttribute("DumpFileName", sourceDumpPath),
                new XAttribute("IniFileName", @"{exml}\dig.ini"),
                new XAttribute("TableInfoFile", @"{exml-1}\TableInfo.xml")));

            var batchImport = new XElement("BatchImport",
                new XAttribute("Language", "de"),
                new XAttribute("HardwareType", "POSPC"),
                new XAttribute("Country", "GER"),
                new XAttribute("TranslationFile", @"{exml-1}\Translate_de.ts"),
                new XAttribute("RefreshTsFile", "False"),
                new XAttribute("BlackListFile", @"{exml-1}\Translate_xx.txt"));

            batchImport.Add(new XComment(" General settings for all ecrs "));
            batchImport.Add(new XElement("ImportXmlDataDir",
                new XAttribute("Path", "{exml}"),
                new XAttribute("Pattern", "support.xml")));

            batchImport.Add(new XElement("SaveDumpFile", new XAttribute("FileName", @"{exml}\support.vpd")));

            root.Add(batchImport);

            var doc = new XDocument(new XDeclaration("1.0", "utf-8", null), root);
            using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
            doc.Save(writer);
        }
    }
}
