using System;
using System.Diagnostics;
using System.IO;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using DumpLoader_2._0.Models;

namespace DumpLoader_2._0.Services
{
    /// <summary>
    /// Drives the third-party VPOS Dump Editor (DIG) to apply the "support mode" DirectAccess
    /// edits to a dump before it gets loaded into VPOS.
    ///
    /// Every file DIG needs (dig.ini, support.exml, support.xml, support.vpd) is generated by
    /// this class into a "VPOSManager" folder created alongside the configured DumpEditor.exe -
    /// nothing is read from or expected to already exist on disk beforehand.
    ///
    /// Pipeline:
    ///  1. Write dig.ini (VPP init settings) and support.xml (the DirectAccess edits: the fixed
    ///     "Local speichern" block, plus one block per enabled DumpModificationOptions checkbox).
    ///  2. Write support.exml, pointing its &lt;LoadDump&gt; at the dump the user selected and at
    ///     the dig.ini/TableInfo.xml/Translate files that ship next to DumpEditor.exe.
    ///  3. Run `DumpEditor.exe support.exml -nogui` and wait for it to finish.
    ///  4. DIG writes the edited copy to support.vpd (the original dump is never touched) - that
    ///     path is returned for VPOS to load instead.
    /// </summary>
    public class DumpEditorService
    {
        private const string WorkFolderName = "VPOSManager";

        /// <summary>Fires for each line DumpEditor.exe writes to stdout or stderr, in order.</summary>
        public event Action<string>? OutputReceived;

        public async Task<string> CreateEditedDumpAsync(string dumpEditorExePath, string sourceDumpPath, DumpModificationOptions options, string? version, string? vppFolderPath)
        {
            if (string.IsNullOrEmpty(dumpEditorExePath))
                throw new ArgumentException("Der Pfad zu DumpEditor.exe ist nicht gesetzt. Bitte in den Einstellungen konfigurieren.", nameof(dumpEditorExePath));

            if (!File.Exists(dumpEditorExePath))
                throw new FileNotFoundException("DumpEditor.exe wurde nicht gefunden.", dumpEditorExePath);

            if (string.IsNullOrEmpty(sourceDumpPath))
                throw new ArgumentException("sourceDumpPath must not be empty.", nameof(sourceDumpPath));

            var dumpEditorRoot = Path.GetDirectoryName(Path.GetFullPath(dumpEditorExePath));
            if (string.IsNullOrEmpty(dumpEditorRoot))
                throw new InvalidOperationException("Das Verzeichnis von DumpEditor.exe konnte nicht ermittelt werden.");

            await InstallVppForVersionAsync(dumpEditorExePath, dumpEditorRoot, version, vppFolderPath);

            var workFolder = Path.Combine(dumpEditorRoot, WorkFolderName);
            Directory.CreateDirectory(workFolder);

            var digIniPath = Path.Combine(workFolder, "dig.ini");
            var supportXmlPath = Path.Combine(workFolder, "support.xml");
            var supportExmlPath = Path.Combine(workFolder, "support.exml");
            var supportDumpOutputPath = Path.Combine(workFolder, "support.vpd");

            WriteDigIni(digIniPath, dumpEditorRoot);
            WriteSupportXml(supportXmlPath, options);
            WriteSupportExml(supportExmlPath, sourceDumpPath);

            if (File.Exists(supportDumpOutputPath))
            {
                try { File.Delete(supportDumpOutputPath); } catch { /* best effort */ }
            }

            var startInfo = new ProcessStartInfo(dumpEditorExePath)
            {
                Arguments = $"\"{supportExmlPath}\" -nogui",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true,
                WorkingDirectory = dumpEditorRoot,
            };

            using var process = new Process { StartInfo = startInfo, EnableRaisingEvents = true };
            process.OutputDataReceived += (_, e) => { if (e.Data != null) OutputReceived?.Invoke(e.Data); };
            process.ErrorDataReceived += (_, e) => { if (e.Data != null) OutputReceived?.Invoke(e.Data); };

            if (!process.Start())
                throw new InvalidOperationException("DumpEditor.exe konnte nicht gestartet werden.");

            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            await process.WaitForExitAsync();

            if (!File.Exists(supportDumpOutputPath))
                throw new FileNotFoundException("DumpEditor hat keine bearbeitete Dump-Datei erzeugt.", supportDumpOutputPath);

            return supportDumpOutputPath;
        }

        /// <summary>
        /// DIG loads each VPOS version's PC dump through a version-specific "VPOSPROG.DLL" that
        /// actually ships as "VPP-{Version}.VPP" files in a shared folder. Before every run, the
        /// file matching the currently selected version is copied over the previous
        /// VPOSPROG.DLL next to DumpEditor.exe, so DIG always loads the dump with the matching
        /// program logic.
        /// </summary>
        private async Task InstallVppForVersionAsync(string dumpEditorExePath, string dumpEditorRoot, string? version, string? vppFolderPath)
        {
            if (string.IsNullOrEmpty(version))
                throw new InvalidOperationException("Es ist keine VPOS-Version ausgewählt, das passende VPP kann nicht ermittelt werden.");

            if (string.IsNullOrEmpty(vppFolderPath))
                throw new InvalidOperationException("Der VPP-Pfad ist nicht konfiguriert. Bitte in den Einstellungen festlegen.");

            if (!Directory.Exists(vppFolderPath))
            {
                // The single most common cause of a mapped network drive (e.g. "K:") suddenly
                // "not existing": drive mappings are tied to the logon session token that created
                // them, and elevating a process (Run as administrator / a UAC-elevated launch)
                // gives it a *different* token that never saw that mapping - so the same drive
                // letter that works fine unelevated reports as missing entirely.
                var hint = IsRunningElevated()
                    ? " VPOS Manager läuft aktuell mit erhöhten Rechten (als Administrator) - zugeordnete Netzlaufwerke des normalen Benutzerkontos sind für elevierte Prozesse nicht sichtbar. Bitte ohne Administratorrechte starten, oder stattdessen den vollständigen UNC-Netzwerkpfad verwenden (z. B. \\\\server\\freigabe\\...)."
                    : " Prüfen Sie, ob das Laufwerk verbunden ist bzw. die Netzwerkverbindung besteht.";
                throw new DirectoryNotFoundException($"Der VPP-Pfad wurde nicht gefunden: {vppFolderPath}.{hint}");
            }

            var vppFileName = $"VPP-{version}.VPP";
            var vppSourcePath = Path.Combine(vppFolderPath, vppFileName);
            if (!File.Exists(vppSourcePath))
                throw new FileNotFoundException($"Kein passendes VPP für Version {version} gefunden ({vppFileName}).", vppSourcePath);

            OutputReceived?.Invoke($"Installing {vppFileName} for version {version}...");

            var vposprogDllPath = Path.Combine(dumpEditorRoot, "VPOSPROG.DLL");
            if (File.Exists(vposprogDllPath))
            {
                // NTFS refuses to delete a file with the ReadOnly attribute set, regardless of
                // the caller's privileges - even an administrator gets "Access denied". VPP files
                // copied in from a read-only network share carry that attribute over, so every
                // run after the first would otherwise fail here. Clear it defensively before
                // deleting.
                ClearReadOnlyAttribute(vposprogDllPath);

                await DeleteWithRetryAsync(vposprogDllPath, dumpEditorExePath);
            }

            File.Copy(vppSourcePath, vposprogDllPath);

            // Also clear it on the freshly copied file, so the *next* run's delete above doesn't
            // hit the same problem again.
            ClearReadOnlyAttribute(vposprogDllPath);

            OutputReceived?.Invoke("VPP installed.");
        }

        /// <summary>
        /// Deletes VPOSPROG.DLL, retrying once after closing any leftover DumpEditor.exe instance
        /// still holding it open. .NET maps "file is locked by another process" to
        /// UnauthorizedAccessException (not IOException, as its message would suggest) via
        /// DeleteFile's ERROR_ACCESS_DENIED - so a lingering instance from a previous, aborted run
        /// looks identical to a genuine permissions problem until this narrows it down.
        /// </summary>
        private async Task DeleteWithRetryAsync(string path, string dumpEditorExePath)
        {
            const int maxAttempts = 3;
            for (var attempt = 1; attempt <= maxAttempts; attempt++)
            {
                try
                {
                    File.Delete(path);
                    return;
                }
                catch (UnauthorizedAccessException) when (attempt < maxAttempts)
                {
                    if (attempt == 1)
                    {
                        OutputReceived?.Invoke("VPOSPROG.DLL is in use - closing any running DumpEditor.exe instance...");
                        CloseRunningInstances(dumpEditorExePath);
                    }
                    await Task.Delay(500);
                }
                catch (UnauthorizedAccessException ex)
                {
                    throw new UnauthorizedAccessException(
                        $"Zugriff auf \"{path}\" verweigert. Die Datei wird vermutlich von einem laufenden " +
                        "DumpEditor.exe- oder VPOSPC.exe-Prozess verwendet, der nicht automatisch geschlossen " +
                        "werden konnte. Bitte alle laufenden Instanzen manuell schließen und erneut versuchen.",
                        ex);
                }
            }
        }

        /// <summary>Closes any running instance of the exact configured DumpEditor.exe (matched by
        /// full module path, not just process name, so an unrelated same-named process elsewhere
        /// is never touched).</summary>
        private static void CloseRunningInstances(string exePath)
        {
            try
            {
                var processName = Path.GetFileNameWithoutExtension(exePath);
                var fullPath = Path.GetFullPath(exePath);

                foreach (var proc in Process.GetProcessesByName(processName))
                {
                    using (proc)
                    {
                        try
                        {
                            string? modulePath = null;
                            try { modulePath = proc.MainModule?.FileName; } catch { /* denied reading another process's module info - fall back to name match below */ }

                            if (modulePath == null || string.Equals(modulePath, fullPath, StringComparison.OrdinalIgnoreCase))
                            {
                                proc.Kill();
                                proc.WaitForExit(3000);
                            }
                        }
                        catch { /* best effort */ }
                    }
                }
            }
            catch { /* best effort */ }
        }

        private static void ClearReadOnlyAttribute(string path)
        {
            try
            {
                var attributes = File.GetAttributes(path);
                if ((attributes & FileAttributes.ReadOnly) != 0)
                    File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
            }
            catch
            {
                // Best effort - if this fails, the delete/copy right after will surface whatever
                // the real problem is.
            }
        }

        private static bool IsRunningElevated()
        {
            try
            {
                using var identity = WindowsIdentity.GetCurrent();
                var principal = new WindowsPrincipal(identity);
                return principal.IsInRole(WindowsBuiltInRole.Administrator);
            }
            catch
            {
                return false;
            }
        }

        /// <summary>
        /// VPP module init settings DIG needs to load the dump. VppPath assumes the standard DIG
        /// layout, where a "VPPs" folder sits directly next to DumpEditor.exe.
        /// </summary>
        private static void WriteDigIni(string path, string dumpEditorRoot)
        {
            var vppPath = Path.Combine(dumpEditorRoot, "VPPs");
            var content =
                "[ProgModuleInit]\r\n" +
                "Size=250\r\n" +
                "HardwareType=8\r\n" +
                "LanguageId=1\r\n" +
                $"VppPath={vppPath}\r\n";

            File.WriteAllText(path, content, new UTF8Encoding(false));
        }

        private static void WriteSupportXml(string path, DumpModificationOptions options)
        {
            var root = new XElement("DIG", new XAttribute("Version", "1.0"));

            // Always included, regardless of which checkboxes are set.
            root.Add(new XComment(" Local speichern - ACHTUNG bei einer POS-PC bitte die Einstellungen in der Datei \"HWPROF.INI\" prüfen! "));
            root.Add(DirectAccess("3", "1", "1", "77", "0"));
            root.Add(DirectAccess("3", "1", "1", "78", "0"));
            root.Add(DirectAccess("3", "1", "1", "83", "0"));
            root.Add(DirectAccess("3", "1", "1", "15", "0"));
            root.Add(DirectAccess("3", "1", "1", "84", "0"));

            if (options.DisablePrint)
            {
                root.Add(new XComment(" Disable Drucken "));
                root.Add(DirectAccess("33", "1", "350", "1", "1"));
            }

            if (options.DisableMyVectron)
            {
                root.Add(new XComment(" Disable myVectron "));
                root.Add(DirectAccess("1021", "1", "1", "3", "0"));
            }

            if (options.DisableVectronConnect)
            {
                root.Add(new XComment(" Disable VectronConnect "));
                root.Add(DirectAccess("780", "1", "1", "1", "Banane"));
                root.Add(DirectAccess("780", "1", "1", "2", "0"));
                root.Add(DirectAccess("780", "1", "1", "12", "0"));
            }
            else if (options.EnableVectronConnect)
            {
                // Writes the same three addresses as DisableVectronConnect above, with opposite
                // intent - MainViewModel refuses to run automatic dump editing if both checkboxes
                // are on at once, so this "else" is a defensive backstop, not the primary guard.
                root.Add(new XComment(" Enable VectronConnect "));
                root.Add(DirectAccess("780", "1", "1", "12", "1"));
                root.Add(DirectAccess("780", "1", "1", "1", options.VectronConnectId ?? string.Empty));
                root.Add(DirectAccess("780", "1", "1", "2", options.VectronConnectPassword ?? string.Empty));
            }

            if (options.DisableLicenseCheck)
            {
                root.Add(new XComment(" Disable Lizenzabruf "));
                root.Add(DirectAccess("695", "1", "1", "1", "0"));
            }

            if (options.DisableBonVito)
            {
                root.Add(new XComment(" Disable bonVito "));
                root.Add(DirectAccess("532", "1", "1", "8", "0"));
            }

            if (options.DisableKeyboardSound)
            {
                root.Add(new XComment(" Disable keyboard sound "));
                root.Add(DirectAccess("3", "1", "1", "20", "0"));
            }

            if (options.DisableErrorSound)
            {
                root.Add(new XComment(" Disable error sound "));
                root.Add(DirectAccess("3", "1", "1", "23", "0"));
            }

            if (options.MyVectronUsernameEnabled)
            {
                root.Add(new XComment(" myVectron Username "));
                root.Add(DirectAccess("1021", "1", "1", "1", options.MyVectronUsername ?? string.Empty));
            }

            if (options.MyVectronPasswordEnabled)
            {
                root.Add(new XComment(" myVectron Password "));
                root.Add(DirectAccess("1021", "1", "1", "2", options.MyVectronPassword ?? string.Empty));
            }

            // Always applied (not opt-in): selects Prod vs. Test server for VectronConnect/myVectron.
            var serverValue = options.IsTestServer ? "1" : "0";
            root.Add(new XComment(options.IsTestServer ? " Server-Umgebung: Test " : " Server-Umgebung: Prod "));
            root.Add(DirectAccess("33", "1", "524", "1", serverValue));
            root.Add(DirectAccess("33", "1", "589", "1", serverValue));

            // Prerequisite for any of the interface 18/19/20 edits below - shared, so only emit it
            // once regardless of how many of the three are actually in use.
            if (options.SetTcpIpInterface20 || options.SetTcpIpInterface19 || options.AddShift4TerminalToInterface18)
            {
                root.Add(new XComment(" Allow up to 20 interfaces "));
                root.Add(DirectAccess("7", "1", "1", "248", "20"));
            }

            if (options.SetTcpIpInterface20)
            {
                root.Add(new XComment(" Set Interface 20 to TCP/IP (PRINTER) - printer routing "));
                root.Add(DirectAccess("441", "1", "20", "1", "PRINTER"));
                root.Add(DirectAccess("441", "1", "20", "2", "6")); // TCP/IP
                root.Add(DirectAccess("441", "1", "20", "23", "9100")); // fixed port, not user-configurable
                WriteIpv4Bytes(root, "20", options.Interface20IpAddress);

                if (options.SetAllPrintersToInterface)
                {
                    root.Add(new XComment(" Set all 10 printers to Interface 20 "));
                    var driverNumber = options.PrinterDriverNumber ?? "20";
                    for (var printerNo = 1; printerNo <= 10; printerNo++)
                    {
                        var recPos = printerNo.ToString();
                        root.Add(DirectAccess("56", "1", recPos, "5", "20")); // interface
                        root.Add(DirectAccess("56", "1", recPos, "3", "1")); // enable programmed driver
                        root.Add(DirectAccess("56", "1", recPos, "2", driverNumber)); // driver number
                    }
                }
            }

            if (options.SetTcpIpInterface19)
            {
                root.Add(new XComment(" Set Interface 19 to TCP/IP (TERMINAL) - PAX, Verifone & MobileApp routing "));
                root.Add(DirectAccess("441", "1", "19", "1", "TERMINAL"));
                root.Add(DirectAccess("441", "1", "19", "2", "6")); // TCP/IP
                root.Add(DirectAccess("441", "1", "19", "23", "8085")); // fixed port, not user-configurable
                WriteIpv4Bytes(root, "19", options.Interface19IpAddress);
            }

            if (options.AddShift4TerminalToInterface18)
            {
                root.Add(new XComment(" Add Shift4 Terminal to Interface 18 (for printing) "));
                root.Add(DirectAccess("441", "1", "18", "1", "TERMDRUCK"));
                root.Add(DirectAccess("441", "1", "18", "2", "9"));
            }

            var doc = new XDocument(new XDeclaration("1.0", "utf-8", null), root);
            using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
            doc.Save(writer);
        }

        /// <summary>IPv4 is stored as four separate byte fields, always at FieldNo 19-22 of the
        /// given interface's RecPos (441/1/{interfaceRecPos}/19..22).</summary>
        private static void WriteIpv4Bytes(XElement root, string interfaceRecPos, string? ipAddress)
        {
            var parts = (ipAddress ?? string.Empty).Split('.');
            for (var i = 0; i < 4; i++)
            {
                var fieldNo = (19 + i).ToString();
                var value = i < parts.Length ? parts[i] : "0";
                root.Add(DirectAccess("441", "1", interfaceRecPos, fieldNo, value));
            }
        }

        private static XElement DirectAccess(string tableNo, string planeNo, string recPos, string fieldNo, string data)
        {
            return new XElement("DirectAccess",
                new XAttribute("TableNo", tableNo),
                new XAttribute("PlaneNo", planeNo),
                new XElement("PutData",
                    new XAttribute("RecPos", recPos),
                    new XAttribute("FieldNo", fieldNo),
                    new XAttribute("Data", data)));
        }

        /// <summary>
        /// Generates the eXml script DIG runs: loads the selected dump using dig.ini +
        /// TableInfo.xml (both shipped next to DumpEditor.exe), imports support.xml's
        /// DirectAccess edits, and saves the result as support.vpd - all relative to the
        /// eXml file's own folder ({exml}) or its parent ({exml-1}, i.e. the DIG install root).
        /// </summary>
        private static void WriteSupportExml(string path, string sourceDumpPath)
        {
            var root = new XElement("DIG", new XAttribute("Version", "1.0"));

            root.Add(new XComment(" Dump file "));
            root.Add(new XElement("LoadDump",
                new XAttribute("DumpFileName", sourceDumpPath),
                new XAttribute("IniFileName", @"{exml}\dig.ini"),
                new XAttribute("TableInfoFile", @"{exml-1}\TableInfo.xml")));

            var batchImport = new XElement("BatchImport",
                new XAttribute("Language", "de"),
                new XAttribute("HardwareType", "POSPC"),
                new XAttribute("Country", "GER"),
                new XAttribute("TranslationFile", @"{exml-1}\Translate_de.ts"),
                new XAttribute("RefreshTsFile", "False"),
                new XAttribute("BlackListFile", @"{exml-1}\Translate_xx.txt"));

            batchImport.Add(new XComment(" General settings for all ecrs "));
            batchImport.Add(new XElement("ImportXmlDataDir",
                new XAttribute("Path", "{exml}"),
                new XAttribute("Pattern", "support.xml")));

            batchImport.Add(new XElement("SaveDumpFile", new XAttribute("FileName", @"{exml}\support.vpd")));

            root.Add(batchImport);

            var doc = new XDocument(new XDeclaration("1.0", "utf-8", null), root);
            using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
            doc.Save(writer);
        }
    }
}
